name: Build

on:
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 16.5

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Build & Test
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test --no-build --configuration Release

    - name: Pack
      run: | 
        mkdir ${{ github.workspace }}/package
        dotnet pack --no-build -c Release --output "${{ github.workspace }}/package"

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: NuGet
        path: ${{ github.workspace }}/package